### ISSUE TITLE
Error - Not Found wp-cli.yml

### ISSUE THREAD

**Issue by robertov8** [conetix/docker-wordpress-wp-cli#2]
Error: The site you have requested is not installed.
Run `wp core install`.
http://wp-cli.org/config/

Hello, I'm trying to run "wp", but I've seen that wp-cli.yml is missing

**Comment by timbutler** [comment]
Hi @robertov82008, generally when you see that error from wp-cli it's because you haven't completed the installation. I've updated the README to avoid future confusion, have you gone through the steps to complete the WordPress install at all?
