### ISSUE TITLE
Environment variables passed to `wp` command not loaded.

### ISSUE THREAD

**Issue by subuta** [conetix/docker-wordpress-wp-cli#3]
My custom `wp-config.php` uses `getEnv`. 
and when I run `DB_HOST='localhost' DB_NAME='wordpress' DB_USER='root' DB_PASSWORD='dummy' wp theme list` command at your docker environment, it not work as expected.

[sample wp-config.php]
```
define('DB_NAME', getEnv('DB_NAME'));
define('DB_USER', getEnv('DB_USER'));
define('DB_PASSWORD', getEnv('DB_PASSWORD'));
define('DB_HOST', getEnv('DB_HOST'));
```

[error]
```
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at ``. This could mean your host’s database server is down.
```

It looks like we need to add `-E` flag at `sudo` command in `wp-su.sh`.
then it works as I expected :) 

[reference]
http://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo

**Comment by timbutler** [comment]
Thanks @subuta, I've updated the sudo command to include -E.
