### ISSUE TITLE
missing mysqldump

### ISSUE THREAD

**Issue by gitowiec** [conetix/docker-wordpress-wp-cli#4]
Can't run wp-cli command
```
wp db export filename.sql
```

After running command
```
docker exec -it name-of-container bash
```

The error is
```
sh: 1: mysqldump: not found
```

**Comment by HardeepAsrani** [comment]
I was facing the same issue for a long time. SSH into you WP container and run:

`apt-get install mysql-client`

It will start working then. I'm forking this repo to start maintaining a new WP with WP-CLI image. This is the most useful so far but lacks active maintenance.

**Comment by timbutler** [comment]
Sorry for the delay, I'd clearly missed the first notification from @gitowiec. I've updated the image to include mysql-client so that it has the ability to dump the database. Please note also the official WordPress Docker images now have a cli variant too, which may or may not be more suitable.

**Comment by HardeepAsrani** [comment]
You updated it the same day I forked it: http://github.com/HardeepAsrani/docker-wordpress-with-wp-cli/ 😆
