### ISSUE TITLE
"Too many positional arguments" error when passing string with whitespace

### ISSUE THREAD

**Issue by t-fritsch** [conetix/docker-wordpress-wp-cli#5]
When trying to pass parameters that contain spaces to wp-cli, I get `Error: Too many positional arguments: ...`

Ex. 
```bash
docker-compose exec web wp option update date_format 'j F Y'
```
returns :
```bash
Error: Too many positional arguments: F Y
```

I've found that changing wp-su file seems to fix the problem, but haven't tested it enough to submit pull request (I'm also not skilled enough in bash scripting to be sure i'm not doing something awful ;) ). The fix is to replace the last argument **`$*`** with **`"$@"`** :
```bash
sudo -E -u www-data /bin/wp-cli.phar "$@"
```

Does that make sense ?

**Comment by timbutler** [comment]
Thanks for reporting this @tfritsch-km, I'll added it into the code. Please note also the official WordPress Docker images now have a cli variant too, which may or may not be more suitable.
